# Generated by Django 5.1.5 on 2025-10-23 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invest', '0004_investmenttier_capital_return'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usdt_bep20',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
